on:
  workflow_call: # This allows other repositories to trigger this workflow
    inputs:
      candidate_repo:
        required: true
        type: string

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Candidate Code
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.candidate_repo }}

      - name: Checkout Test Suite
        uses: actions/checkout@v4
        with:
          repository: 00kaku/github-timeline-test-suite
          path: test-suite

      - name: Install Dependencies
        run: |
          composer install --working-dir=test-suite
          composer install

      - name: Run Tests
        run: vendor/bin/phpunit --bootstrap test-suite/bootstrap.php test-suite/tests
